<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>The Vulnerator - Attack <?= $url ?></title>
    <meta name="description" content="Vulnerabilities searching testing online">
    <meta name="author" content="george popoff">

    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <![endif]-->
</head>
<body>

<header>
    <ul>
        <li>
            <?php echo $this->tag->linkTo(
                "",
                "Домой"
            )?>
        </li>
        <li>
            <?php echo $this->tag->linkTo(
                    "signup",
                    "Войти"
            )?>
        </li>
        <li>
            <?php echo $this->tag->linkTo(
                "signin",
                "Регистрация"
            )?>
        </li>
    </ul>
</header>

<h1>Result of scanning web, starting in <?= $url ?>: </h1>
<p>Total sites scanned: <strong><?= count($vulnerabilities) ?></strong> </p>
<table>
    <caption>Resulting table</caption>
    <tr>
        <th>Site url</th>
        <th>Total score</th>
        <th>Vulnerabilities</th>
    </tr>

    <?php foreach( $vulnerabilities as $site => $vulnerability ): ?>
        <tr>
            <td><?= $site ?></td>
            <td><?= $vulnerability["score"] ?></td>
            <td>
                <ol>
                    <?php foreach( $vulnerability["list"] as $item ): ?>
                        <li><?= $item ?></li>
                    <?php endforeach; ?>
                </ol>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</body>
</html>